### ISSUE TITLE
Primera pantalla

### ISSUE THREAD

**Issue by AlexandrUlyanov** [JonJairo/osinadevs#1]
- [x] Indicador de carga del mapa
- [x] Cambiar el botón (añadir animación)
- [x] Corregir la animación del logotipo (Web)
- [x] Mejorar las nubes y su animación 
- [x] controles OnOff.

**Comment by Thegod322** [comment]
Empiezo con esta tarea, voy a ir en orden 

- Nubes

- Logo(anim)

-  Botón

**Comment by Thegod322** [comment]
He realizado la animación de las nubes utilizando GSAP. Además, he investigado más sobre animaciones y cómo abordar diferentes implementaciones. After Effects no era la mejor opción para las nubes, ya que consumía 6 GB de RAM para mover una sola imagen. Actualmente, muevo tres a través del código.

**Comment by Thegod322** [comment]
Estuve haciendo Hoy la animacion de la carga, pero me encontre con un problema, parece que el export a SVG no soporta curvas de las animaciones (ease in / out). ademas me enfrente con crashes del after effect, he averiguado que el after effects guarda un monton de cache a la hora de trabajar y si no hay memoria suficiente en el disco, el after effects crashea. 

Animacion de carga esta casi terminada.
Indicador de la carga esta terminado pero hay que testearlo con la nueva animacion (sin curvas).

al terminar con la animacion me paso al boton y termino la sequencia Inicial

**Comment by Thegod322** [comment]
tengo la animacion y el indicador, ahora estoy finalizando la sequencia y paso al boton

**Comment by JonJairo** [comment]
> tengo la animacion y el indicador, ahora estoy finalizando la sequencia y paso al boton

Y donde esta?

**Comment by JonJairo** [comment]
Parece que se termina en Breves El loading. Anim end hover y click

**Comment by Thegod322** [comment]
tenia terminadas las animaciones durante bastante tiempe pero ne veia la manera de exportarlas. Al final hemos aceptado el pipeline de after effects y ahora tengo que entregar los JSON.

**Comment by Thegod322** [comment]
[JsonUiIcons.zip](https://github.com/user-attachments/files/15849365/JsonUiIcons.zip)

Iconos y animaciones de La Ui

**Comment by JonJairo** [comment]
> [JsonUiIcons.zip](https://github.com/user-attachments/files/15849365/JsonUiIcons.zip)
> 
> Iconos y animaciones de La Ui



[sendablesJairo.zip](https://github.com/user-attachments/files/15849401/sendablesJairo.zip)

**Comment by Thegod322** [comment]
![Image](https://github.com/JonJairo/osinadevs/assets/48012636/c17a73cf-5455-474f-a6dd-1c27ff859fa0)

Esto es la ultima version de la interfaz despues de la sequencia

**Comment by Thegod322** [comment]
[simpleAnim1.json](https://github.com/user-attachments/files/15858977/simpleAnim1.json)
[simpleAnim2.json](https://github.com/user-attachments/files/15858976/simpleAnim2.json)
simple anim1:
0-10s loading loop
10-11s fade out after loading (Dissapear) 

cuando primera animacion disaparece, tiene que aparecer la segunda - SimpleAnim 2. Asi, toda la sequencia se mantiene en una solo linea de tiempo 




simple anim2 : 
0s - 1s
fade in 
1s Idle button
1s- 1.20s Hover anim 
1.20s-2.21s Hover Idle state
2.21s - 7s final animation sequence

**Comment by Thegod322** [comment]
[IconsExportSVG.zip](https://github.com/user-attachments/files/15866254/IconsExportSVG.zip)

Iconos en SVG
