### ISSUE TITLE
Preparar los botones para la exportación

### ISSUE THREAD

**Issue by AlexandrUlyanov** [JonJairo/osinadevs#2]

**Comment by Thegod322** [comment]
He adivinado la manera correcta de exportar los SVG para hacer las animaciones. Aquí están los SVG staticos
[ButtonsSVG.zip](https://github.com/user-attachments/files/15550922/ButtonsSVG.zip)

**Comment by AlexandrUlyanov** [comment]
Es necesario estandarizar los íconos en cuanto al grosor de las líneas y los tamaños. Es necesario elegir un grosor y mantener un estilo uniforme. Sería bueno que los círculos en los íconos tuvieran el mismo tamaño. En general, todo está bien.

**Comment by JonJairo** [comment]
![Image](https://github.com/JonJairo/osinadevs/assets/35713957/498886fe-6056-4338-81ad-8b314bd2a26b)
